application: finderful
version: 1
api_version: 1
runtime: python27
threadsafe: true

libraries:
- name: django
  version: "1.2"

handlers:
- url: /css
  static_dir: css

- url: /.*
  script: main.app


